agency: General Services Administration
site_title: "GSA Site Scan Dashboard"
description: "Proof of concept for a simple yet customizable JS-based site scanner dashboard."

# Desired scans 
# Note: domains does not need to be included here, 
# because any scans in domainlist will be scanned and displayed.
scans:
    - dap

# This is the list of domains which we want to be scanned and displayed for the above agency.
# Note: that www is routinely stripped from master list of domains in the site scanner
# (https://github.com/GSA/data/blob/master/dotgov-websites/pulse-subdomains-snapshot-06-08-2020-https.csv)
# So www.domain.gov should probably be here as just domain.gov
# When in doubt, search that list for your best match. 
domainlist:
    - fedpay.gsa.gov
    - finance.ocfo.gsa.gov 
    - financeweb.gsa.gov
    - vcss.ocfo.gsa.gov 
    - apps.ocfo.gsa.gov 
    - 1.usa.gov
    - 10x.gsa.gov
    - 18f.gsa.gov
    - aas.gsa.gov
    - accessibility.18f.gov
    - accessibility.digital.gov
    - agile-labor-categories.18f.gov
    - agile.18f.gov
    - amp.fas.gsa.gov
    - analytics.fr.cloud.gov
    - analytics.usa.gov
    - api-all-the-x.18f.gov
    - api-program.18f.gov
    - api-usability-testing.18f.gov
    - atf-eregs.18f.gov
    - atf-eregs.app.cloud.gov
    - before-you-ship.18f.gov
    - beta.SAM.gov 
    - blog.usa.gov
    - brand.18f.gov
    - calc-dev.app.cloud.gov
    - calc.gsa.gov 
    - cars.fas.gsa.gov
    - catalog.data.gov
    - challenge.gov 
    - chat.18f.gov
    - climate.data.gov
    - cloud.gov
    - cm-jira.usa.gov
    - cmls.gsa.gov 
    - code.gov
    - coe.gsa.gov
    - college-scorecard.app.cloud.gov
    - collegescorecard.ed.gov
    - compliance-viewer.18f.gov
    - components.designsystem.digital.gov
    - computersforlearning.gov
    - conectate.gobiernousa.gov
    - connect.usa.gov
    - content-guide.18f.gov
    - cpars.gov 
    - Cpsearch.fas.gsa.gov 
    - crime-data-explorer.fr.cloud.gov
    - designsystem.digital.gov
    - developers.code.gov
    - developers.login.gov
    - digital-acquisition-playbook.18f.gov
    - digitaldashboard.gov
    - discovery.gsa.gov 
    - dolores-app.18f.gov
    - drivethru.gsa.gov
    - ebuy.gsa.gov
    - emerging.digital.gov
    - eng-hiring.18f.gov
    - engineering.18f.gov
    - eoffer.gsa.gov 
    - epa-notice.usa.gov
    - faq.coronavirus.gov
    - federalist-docs.18f.gov
    - federalist-report-template.18f.gov
    - federation.data.gov
    - fedramp.gov
    - fedsim.gsa.gov
    - fedspecs.gsa.gov 
    - feedback.usa.gov
    - fellows-in-innovation.pif.gov
    - ffms.fas.gsa.gov
    - findtreatment.gov
    - fleet.fas.gsa.gov
    - fleeteur.fas.gsa.gov
    - fmvrs.fas.gsa.gov
    - fpds.gov 
    - fugacious.18f.gov
    - go.usa.gov
    - govconnect.18f.gov
    - gsaadvantage.gov 
    - gsaelibrary.gsa.gov
    - gsaglobalsupply.gsa.gov 
    - gsaxcess.gov
    - gsaxcesspractice.fas.gsa.gov
    - hallways.cap.gsa.gov
    - handbook.tts.gsa.gov
    - identity-dev-docs.18f.gov
    - innovation-toolkit-prototype.18f.gov
    - interact.gsa.gov
    - join.tts.gsa.gov
    - labs.data.gov
    - labs.usa.gov
    - login.gov
    - lookforwatersense-prod.app.cloud.gov
    - markdown-helper.18f.gov
    - marketplace.fedramp.gov
    - methods.18f.gov
    - mysales.fas.gsa.gov
    - open-forest-dev.app.cloud.gov
    - open-source-guide.18f.gov
    - open-source-program.18f.gov
    - openopps.digitalgov.gov
    - participation.usa.gov
    - paygap.pif.gov
    - performance-gov-research.18f.gov
    - pfabankapi.app.cloud.gov
    - pfabankfindui-d.app.cloud.gov
    - pfabankfindui-q.app.cloud.gov
    - pfabankfindui.app.cloud.gov
    - pfabankui-q.app.cloud.gov
    - plain-language-tutorial.18f.gov
    - pra.digital.gov
    - presidentialinnovationfellows.gov
    - private-eye.18f.gov
    - product-guide.18f.gov
    - publications.usa.gov
    - resources.data.gov
    - sbst.gov
    - sdg-bsp.data.gov
    - sdg.data.gov
    - search.gov
    - secure.login.gov
    - site-scanning.app.cloud.gov
    - smartpay.gsa.gov
    - strategy.data.gov
    - tailored.fedramp.gov
    - tophealth.pif.gov
    - touchpoints.digital.gov


# ANALYTICS
google_analytics_ua: ''
