agency: General Services Administration
site_title: "GSA Site Scan Dashboard"
description: "Proof of concept for a simple yet customizable JS-based site scanner dashboard."

# Desired scans 
# Note: domains does not need to be included here, 
# because any scans in domainlist will be scanned and displayed.
scans:
    - dap

# This is the list of domains which we want to be scanned and displayed for the above agency.
# Note: that www is routinely stripped from master list of domains in the site scanner
# (https://github.com/GSA/data/blob/master/dotgov-websites/pulse-subdomains-snapshot-06-08-2020-https.csv)
# So www.domain.gov should probably be here as just domain.gov
# When in doubt, search that list for your best match. 
domainlist:
    - disposal.gsa.gov
    - extportal.pbs.gsa.gov
    - GSAfinearts.pbs.gsa.gov
    - mysmartplans.gsa.gov
    - NCRrecycles.gsa.gov
    - propertydisposal.gsa.gov
    - publiccourts.gsa.gov

# ANALYTICS
google_analytics_ua: ''
