agency: General Services Administration
site_title: "GSA Site Scan Dashboard"
description: "Proof of concept for a simple yet customizable JS-based site scanner dashboard."

# Desired scans 
# Note: domains does not need to be included here, 
# because any scans in domainlist will be scanned and displayed.
scans:
    - dap

# This is the list of domains which we want to be scanned and displayed for the above agency.
# Note: that www is routinely stripped from master list of domains in the site scanner
# (https://github.com/GSA/data/blob/master/dotgov-websites/pulse-subdomains-snapshot-06-08-2020-https.csv)
# So www.domain.gov should probably be here as just domain.gov
# When in doubt, search that list for your best match. 
domainlist:
    - fedpay.gsa.gov
    - finance.ocfo.gsa.gov 
    - financeweb.gsa.gov
    - vcss.ocfo.gsa.gov 
    - apps.ocfo.gsa.gov 
    - 1.usa.gov
    - 10x.gsa.gov
    - 18f.gsa.gov
    - aas.gsa.gov
    - accessibility.18f.gov
    - accessibility.digital.gov
    - agile-labor-categories.18f.gov
    - agile.18f.gov
    - amp.fas.gsa.gov
    - analytics.fr.cloud.gov
    - analytics.usa.gov
    - api-all-the-x.18f.gov
    - api-program.18f.gov
    - api-usability-testing.18f.gov
    - atf-eregs.18f.gov
    - atf-eregs.app.cloud.gov
    - before-you-ship.18f.gov
    - beta.SAM.gov 
    - blog.usa.gov
    - brand.18f.gov

# ANALYTICS
google_analytics_ua: ''
