agency: General Services Administration
site_title: "GSA Site Scan Dashboard"
description: "Proof of concept for a simple yet customizable JS-based site scanner dashboard."

# Desired scans 
# Note: domains does not need to be included here, 
# because any scans in domainlist will be scanned and displayed.
scans:
    - dap

# This is the list of domains which we want to be scanned and displayed for the above agency.
# Note: that www is routinely stripped from master list of domains in the site scanner
# (https://github.com/GSA/data/blob/master/dotgov-websites/pulse-subdomains-snapshot-06-08-2020-https.csv)
# So www.domain.gov should probably be here as just domain.gov
# When in doubt, search that list for your best match. 
domainlist:
    - 1.usa.gov
    - 10x.gsa.gov
    - 18f.gsa.gov
    - accessibility.18f.gov
    - accessibility.digital.gov
    - admin-catalog.data.gov
    - admin.digitalgov.gov
    - agile-labor-categories.18f.gov
    - agile.18f.gov
    - analytics.fr.cloud.gov
    - analytics.usa.gov
    - answers.usa.gov
    - api.code.gov
    - api.data.gov
    - api.usa.gov
    - app.cloud.gov
    - apply.pif.gov
    - apps.usa.gov
    - asis.search.gov
    - autoapi.18f.gov
    - autodiscover.apps.gov
    - before-you-ship.18f.gov
    - beta.vote.gov
    - blog.gobiernousa.gov
    - blog.usa.gov
    - blogging-guide.18f.gov
    - brand.18f.gov
    - buscador.usa.gov
    - businessusa.gov
    - catalog.data.gov
    - challenge.gov
    - chat.18f.gov
    - citizenscience.gov
    - cld.epa.gov
    - climate-data-user-study.18f.gov
    - cloud.gov
    - cm-jira.usa.gov
    - code.gov
    - coe.gsa.gov
    - college-scorecard.app.cloud.gov
    - components.designsystem.digital.gov
    - computersforlearning.gov
    - connect.usa.gov
    - content-guide.18f.gov
    - dap.digitalgov.gov
    - dashboard-labs.data.gov
    - data.gov
    - demo.digitalgov.gov
    - demo.touchpoints.digital.gov
    - designsystem.digital.gov
    - developers.login.gov
    - digital.gov
    - discovery.gsa.gov
    - docs.cloud.gov
    - emerging.digital.gov
    - eng-hiring.18f.gov
    - engineering.18f.gov
    - faq.coronavirus.gov
    - federalist-builder.18f.gov
    - federalist-docs-staging.18f.gov
    - federalist-docs.18f.gov
    - federalist-landing-template.18f.gov
    - federalist-modern-team-template.18f.gov
    - federalist-proxy.app.cloud.gov
    - federalist-report-template.18f.gov
    - federalist-staging.18f.gov
    - federalist-uswds-template.18f.gov
    - federalist.18f.gov
    - federalistapp-staging.18f.gov
    - federalistapp.18f.gov
    - federation.data.gov
    - fedinfo.gov
    - fedramp.gov
    - fedspendingtransparency.18f.gov
    - feedback.usa.gov
    - fellows-in-innovation.pif.gov
    - files.18f.gov
    - find.search.gov
    - findtreatment.gov
    - fr.cloud.gov
    - frontend.18f.gov
    - go.usa.gov
    - gobierno.usa.gov
    - gobiernousa.gov
    - govconnect.18f.gov
    - grafana.18f.gov
    - gsaforecast.gsa.gov
    - handbook.tts.gsa.gov
    - https.app.cloud.gov
    - https.cio.gov
    - i14y.usa.gov
    - identity-dev-docs.18f.gov
    - identitysandbox.gov
    - idmanagement.gov
    - idp.brody.identitysandbox.gov
    - idp.ci.identitysandbox.gov
    - idp.crissupb.identitysandbox.gov
    - idp.dev.identitysandbox.gov
    - idp.int.identitysandbox.gov
    - idp.jjg.identitysandbox.gov
    - idp.markryan.identitysandbox.gov
    - idp.qa.identitysandbox.gov
    - idp.staging.login.gov
    - innovation.gov
    - inventory.data.gov
    - jobkit.data.gov
    - jobs.18f.gov
    - join.18f.gov
    - join.tts.gsa.gov
    - kibana.search.usa.gov
    - kids.usa.gov
    - labs-bsp.data.gov
    - labs.data.gov
    - labs.usa.gov
    - login.fr.cloud.gov
    - login.gov
    - marketplace.fedramp.gov
    - methods.18f.gov
    - my.usa.gov
    - new.vote.gov
    - o166.email.digitalgov.gov
    - open-staging.usa.gov
    - open.foia.gov
    - open.usa.gov
    - openopps.digitalgov.gov
    - paid-leave-prototype.18f.gov
    - participation.usa.gov
    - partnership-playbook.18f.gov
    - paygap-slack.pif.gov
    - paygap.pif.gov
    - performance-gov-research.18f.gov
    - performance.gov
    - pif.gov
    - piv.idmanagement.gov
    - pivcac.prod.login.gov
    - plainlanguage.gov
    - pra.digital.gov
    - presidentialinnovationfellows.gov
    - private-eye.18f.gov
    - product-guide.18f.gov
    - promotions.usa.gov
    - proposal.pif.gov
    - public-sans.digital.gov
    - publications.usa.gov
    - pulse.cio.gov
    - qa.identitysandbox.gov
    - registry.usa.gov
    - resources.data.gov
    - review.pif.gov
    - sdg-bsp.data.gov
    - sdg.data.gov
    - search.data.gov
    - search.gov
    - secure.login.gov
    - staging.pulse.cio.gov
    - strategy.data.gov
    - support.digitalgov.gov
    - tailored.fedramp.gov
    - tell-us.usa.gov
    - tellus.usa.gov
    - test.18f.us
    - test.collegescorecard.ed.gov
    - tmate.18f.gov
    - tophealth.pif.gov
    - touchpoints.digital.gov
    - usa.gov
    - usdigitalregistry.digitalgov.gov
    - v1.designsystem.digital.gov
    - vote.gov
    - wp-bsp.data.gov
    - writing-lab-guide.18f.gov

# ANALYTICS
google_analytics_ua: ''
